# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eea2e1f5c73814f8968accefba9bfcbd542f0766772a8dd674ac289febe707ad9da2bf383c3bdeaf445e871a5977261a7efff2342e4fba7e651b8bb710dd8f65

test:
  secret_key_base: 80d220fd338155e61db6dda5c1947c5a20adcbe210af1b5ba41819d84be785458fe24d196041bf686f21065f618940860bcb742375f1192c289ec60c189ae8d3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
